name: lacework-iac-scan-test
# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: 
          - master
          - feature-branch
    pull_request:
        branches:
            - master
            - feature-branch
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
    # This workflow contains a single job called "build"
      build:
        # The type of runner that the job will run on
        runs-on: ubuntu-24.04
        
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            #Install Terraform Latest Version
            - name: Install Terraform CLI
              uses: hashicorp/setup-terraform@v3
             
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout Code
              uses: actions/checkout@v4
              
            - name: Create environment variables file
              # Create an environment variable file that would be passed to the IaC docker image. Note that all relevant environment values need to be passed through here.
              run: |
                env | grep "GITHUB_\|LW_\|CI_" > env.list
                echo $ENV_LW_ACCOUNT
                echo "LW_ACCOUNT=${{ secrets.LW_ACCOUNT }}" >> env.list
                echo "LW_API_KEY=${{ secrets.LW_API_KEY }}" >> env.list
                echo "LW_API_SECRET=${{ secrets.LW_API_SECRET }}" >> env.list
                echo "EXIT_FLAG=Critical=1" >> env.list
                cat env.list
                
            - name: Scan the repo for vulnerabilities in IaC
              run: |
                docker run --env-file env.list -v "$(pwd):/app/src" -w /app/src lacework/codesec:latest lacework iac scan --directory=.

            # Terraform Init
            - name: Terraform init
              run: terraform init
